### ISSUE TITLE
Resource exhaust error

### ISSUE THREAD

**Issue by chaolyang** [JamesGu14/BERT-NER-CLI#2]
I use the same GPU on Google Colab as you but I get

```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[16,16,128,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node bert/encoder/layer_10/attention/self/transpose_2 (defined at /content/drive/My Drive/ai/bert/modeling.py:734) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[node loss/Sum_1 (defined at /content/drive/My Drive/ai/bert_ner.py:346) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

I decreased the batch size from 32 to 16 but still getting this error. Any idea why?

**Comment by chaolyang** [comment]
I found the reason. It was because I was using the large model not the base BERT model.

**Comment by chaolyang** [comment]
My next problem is about running `python predict_cli.py`. After I ran training on Google Colab I have these files under `result_dir` but no `bert_config.json` or `vocab.txt` which are required to run the evaluation. Any instruction is appreciated.

<img width="215" alt="screenshot 2019-02-07 17 41 36" src="https://user-images.githubusercontent.com/44872287/52447740-abde2400-2aff-11e9-9d85-7abf923d368e.png">
